django_celery/picproject/picproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('pictures.views',
    url(r'^album/$', 'album', kwargs={'id':None}, name='albums'),
    url(r'^album/(?P<id>\d+)$', 'album', name='album'),
)
urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

django_celery/picproject/pictures/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
import tasks

    
class Album(models.Model):

    name = models.CharField(max_length=100)
    set_id = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name
        
    @models.permalink
    def get_absolute_url(self):
        return ('album', (), {'id':self.pk})


class Picture(models.Model):

    image_url = models.URLField()
    album = models.ForeignKey('pictures.Album')
    location = models.CharField(max_length=200, blank=True, null=True)
    map_url = models.URLField(blank=True, null=True)
    

django_celery/picproject/pictures/forms.py
from django import forms
from pictures.models import Album


class AlbumForm(forms.ModelForm):

    class Meta:
        model=Album

django_celery/picproject/pictures/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from pictures.models import Album
from pictures.forms import AlbumForm
from pictures import tasks


def album(request, id=None):
    albums = Album.objects.all()
    form = AlbumForm
    res = None
    if id is not None:
        album = get_object_or_404(albums, id=id)
    else:
        album = None
    
    if request.method=='POST':
        form = AlbumForm(request.POST)
        if form.is_valid():
            messages.success(request, 'Album saved, fetching images')
            instance = form.save()
            res = tasks.process_pictures.delay(kwargs['instance'])
            return redirect('album', id=instance.pk)
        
    return render(
        request,
        'index.html',
        {
            'album':album,
            'albums':albums,
            'form': form,
            'res':res
        }
        
    )

django_celery/picproject/picproject/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Pictures - Celery Powered</title>
    <meta charset='UTF-8' />
    <style>
      body {
        font: 100% "Droid Sans", Helvetica, sans-serif;
      }
      form {
        float:right;
        width:20em;
      }
      #albums {
        clear:right;
        float:right;
        width:20em;
        list-style: decimal inside;
      }
      .pic {
        display: block;
      }
    </style>
  </head>
  <body>
  {% if messages %}
      

  <ul id="messages">
    {% for message in messages %}
      <li>{{message}}</li>
    {% endfor %}

      
  </ul>
  {% endif %}  
  <form action="/album/" method="post">{% csrf_token %}
      <h2>New Album</h2>
      {{form.as_p}}
  
      <p><input type="submit" value="Save" /></p>
  </form>
  <ol id="albums">
      <li><a href="/album/">home</li>
    {% for album in albums %}
      <li><a href="{{album.get_absolute_url}}">{{album}}</a> ({{album.picture_set.all|length}})</li>
    {% endfor %}
  </ol>
  {% if album %}
  <h1>{{album.name}} - ({{album.picture_set.all|length}}) pics</h1>
  <p>{{res.ready}} | {{res.get}} | {{res.successful}}</p>
  <ul id="album">
      {% for img in album.picture_set.all %}
<<<<<<< HEAD
       <li>
           <img class="pic" src="{{img.image_url}}" />
           <p><img src="{{img.map_url}}"/> 
           {{img.location}}</p>
       </details></li>
=======
      <li><img src="{{img.image_url}}" />
        {% if img.location %}
          {{img.location}}
          <img src="{{img.map_url}}">
        {% endif %}
      </li>

>>>>>>> 5a2a963e504acfd60ceb92dae3eb06d7d0f06798
      {% endfor %}
  </ul>
  {% endif %}  
  </body>
</html>